version: '3.8'

services:
  estacionei-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - data-protection-keys:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=EstacioneiDB;User=sa;Password=P@ssw0rd123!;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    entrypoint: ["dotnet", "Estacionei.dll"]  

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd123!
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  adminer:
    image: adminer:latest
    ports:
      - "8082:8080"  
    environment:
      - ADMINER_DEFAULT_SERVER=sqlserver

volumes:
  data-protection-keys:
    driver: local
  sql-data:
    driver: local
